task: pathvqa_test
test_split: test
metric_list:
  - metric: overall_acc
    aggregation: !function utils.pathvqa_aggregate_overall_acc
    higher_is_better: true
  - metric: yesno_acc
    aggregation: !function utils.pathvqa_aggregate_yesno_acc
    higher_is_better: true
  - metric: freeform_acc
    aggregation: !function utils.pathvqa_aggregate_freeform_acc
    higher_is_better: true
  - metric: macro_f1
    aggregation: !function utils.pathvqa_aggregate_macro_f1
    higher_is_better: true
  - metric: bleu1
    aggregation: !function utils.pathvqa_aggregate_bleu1
    higher_is_better: true
  - metric: bleu2
    aggregation: !function utils.pathvqa_aggregate_bleu2
    higher_is_better: true
  - metric: bleu3
    aggregation: !function utils.pathvqa_aggregate_bleu3
    higher_is_better: true
  - metric: submission
    aggregation: !function utils.pathvqa_aggregate_submissions
    higher_is_better: true
include: _default_template_pathvqa_yaml
